#include <string.h>
#include "stdio.h"
char test[]="<!DOCTYPE html> <body> <header> <h1>Mini Robot Cleaner</h1> </header> <main> <div class=\"test-area\"> <button class=\"button-style\" onclick=\"inputIP()\">Connect Socket</button> <button class=\"button-style\" onclick=\"sendData()\">Send to Socket</button> <button class=\"button-style\" onclick=\"closeSocket()\">Close Socket</button> </div> </main> </body> <style> *{ font-family: monospace; font-size: 18px; } body { overflow: hidden; background-color: #0a0a23;; margin: 0; color: #f8f8f2; } header { text-align: center; background-color: #0a0a23; text-align: center; } header h1 { font-size: 24px; } main { background-color: #1b1b32; height: 100vh; width: 100%; } .button-style { padding: 5px 20px; background-color: #0a0a23; color: #ffffff; border-radius: 5px; } .test-area { padding-top: 20px; width: 70%; margin: 0 auto; display: flex; justify-content: space-between; flex-direction: row; flex-wrap: wrap; } </style> <script> var socket = null; function sendData() { if(socket!=null) { socket.send(\"Hello\"); } } function connectSocket(ipaddr) { console.log(\"wsl://\"+ipaddr+\":80\"); socket = new WebSocket(\"ws://\"+ipaddr+\":80\"); if(socket!=null) { socket.onopen = function(){ console.log(\"Connected\"); } socket.onerror = function (error) { console.log('Web Socket Error ', error); alert('Web Socket Error ', error); }; socket.onmessage = function(message){ console.log(\"Received: \"); console.log(message) }; } } function closeSocket() { if(socket!=null) { socket.close(); console.log(\"Closed socket\"); } } function inputIP() { let text; var ipaddr = prompt(\"Please enter robot's IP and port:\", \"\"); text = \"Entered IP: \" + ipaddr + \".\"; connectSocket(ipaddr); } </script> </html>";


int main()
{
    printf("%li",strlen(test));
    return 0;
}