################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F1xx_HAL_Driver/Src \
ESP_Driver \
LCD/gui \
LCD/lcd_core \
LCD/lvgl \
LCD/lvgl/lvgl-v8.3/demos/benchmark/assets \
LCD/lvgl/lvgl-v8.3/demos/benchmark \
LCD/lvgl/lvgl-v8.3/demos/keypad_encoder \
LCD/lvgl/lvgl-v8.3/demos/music/assets \
LCD/lvgl/lvgl-v8.3/demos/music \
LCD/lvgl/lvgl-v8.3/demos/stress \
LCD/lvgl/lvgl-v8.3/demos/widgets/assets \
LCD/lvgl/lvgl-v8.3/demos/widgets \
LCD/lvgl/lvgl-v8.3/env_support/rt-thread \
LCD/lvgl/lvgl-v8.3/env_support/rt-thread/squareline \
LCD/lvgl/lvgl-v8.3/examples/anim \
LCD/lvgl/lvgl-v8.3/examples/assets \
LCD/lvgl/lvgl-v8.3/examples/assets/emoji \
LCD/lvgl/lvgl-v8.3/examples/event \
LCD/lvgl/lvgl-v8.3/examples/get_started \
LCD/lvgl/lvgl-v8.3/examples/layouts/flex \
LCD/lvgl/lvgl-v8.3/examples/layouts/grid \
LCD/lvgl/lvgl-v8.3/examples/libs/bmp \
LCD/lvgl/lvgl-v8.3/examples/libs/ffmpeg \
LCD/lvgl/lvgl-v8.3/examples/libs/freetype \
LCD/lvgl/lvgl-v8.3/examples/libs/gif \
LCD/lvgl/lvgl-v8.3/examples/libs/png \
LCD/lvgl/lvgl-v8.3/examples/libs/qrcode \
LCD/lvgl/lvgl-v8.3/examples/libs/rlottie \
LCD/lvgl/lvgl-v8.3/examples/libs/sjpg \
LCD/lvgl/lvgl-v8.3/examples/others/fragment \
LCD/lvgl/lvgl-v8.3/examples/others/gridnav \
LCD/lvgl/lvgl-v8.3/examples/others/ime \
LCD/lvgl/lvgl-v8.3/examples/others/imgfont \
LCD/lvgl/lvgl-v8.3/examples/others/monkey \
LCD/lvgl/lvgl-v8.3/examples/others/msg \
LCD/lvgl/lvgl-v8.3/examples/others/snapshot \
LCD/lvgl/lvgl-v8.3/examples/porting \
LCD/lvgl/lvgl-v8.3/examples/scroll \
LCD/lvgl/lvgl-v8.3/examples/styles \
LCD/lvgl/lvgl-v8.3/examples/widgets/animimg \
LCD/lvgl/lvgl-v8.3/examples/widgets/arc \
LCD/lvgl/lvgl-v8.3/examples/widgets/bar \
LCD/lvgl/lvgl-v8.3/examples/widgets/btn \
LCD/lvgl/lvgl-v8.3/examples/widgets/btnmatrix \
LCD/lvgl/lvgl-v8.3/examples/widgets/calendar \
LCD/lvgl/lvgl-v8.3/examples/widgets/canvas \
LCD/lvgl/lvgl-v8.3/examples/widgets/chart \
LCD/lvgl/lvgl-v8.3/examples/widgets/checkbox \
LCD/lvgl/lvgl-v8.3/examples/widgets/colorwheel \
LCD/lvgl/lvgl-v8.3/examples/widgets/dropdown \
LCD/lvgl/lvgl-v8.3/examples/widgets/img \
LCD/lvgl/lvgl-v8.3/examples/widgets/imgbtn \
LCD/lvgl/lvgl-v8.3/examples/widgets/keyboard \
LCD/lvgl/lvgl-v8.3/examples/widgets/label \
LCD/lvgl/lvgl-v8.3/examples/widgets/led \
LCD/lvgl/lvgl-v8.3/examples/widgets/line \
LCD/lvgl/lvgl-v8.3/examples/widgets/list \
LCD/lvgl/lvgl-v8.3/examples/widgets/menu \
LCD/lvgl/lvgl-v8.3/examples/widgets/meter \
LCD/lvgl/lvgl-v8.3/examples/widgets/msgbox \
LCD/lvgl/lvgl-v8.3/examples/widgets/obj \
LCD/lvgl/lvgl-v8.3/examples/widgets/roller \
LCD/lvgl/lvgl-v8.3/examples/widgets/slider \
LCD/lvgl/lvgl-v8.3/examples/widgets/span \
LCD/lvgl/lvgl-v8.3/examples/widgets/spinbox \
LCD/lvgl/lvgl-v8.3/examples/widgets/spinner \
LCD/lvgl/lvgl-v8.3/examples/widgets/switch \
LCD/lvgl/lvgl-v8.3/examples/widgets/table \
LCD/lvgl/lvgl-v8.3/examples/widgets/tabview \
LCD/lvgl/lvgl-v8.3/examples/widgets/textarea \
LCD/lvgl/lvgl-v8.3/examples/widgets/tileview \
LCD/lvgl/lvgl-v8.3/examples/widgets/win \
LCD/lvgl/lvgl-v8.3/src/core \
LCD/lvgl/lvgl-v8.3/src/draw/arm2d \
LCD/lvgl/lvgl-v8.3/src/draw \
LCD/lvgl/lvgl-v8.3/src/draw/nxp/pxp \
LCD/lvgl/lvgl-v8.3/src/draw/nxp/vglite \
LCD/lvgl/lvgl-v8.3/src/draw/sdl \
LCD/lvgl/lvgl-v8.3/src/draw/stm32_dma2d \
LCD/lvgl/lvgl-v8.3/src/draw/sw \
LCD/lvgl/lvgl-v8.3/src/draw/swm341_dma2d \
LCD/lvgl/lvgl-v8.3/src/extra/layouts/flex \
LCD/lvgl/lvgl-v8.3/src/extra/layouts/grid \
LCD/lvgl/lvgl-v8.3/src/extra/libs/bmp \
LCD/lvgl/lvgl-v8.3/src/extra/libs/ffmpeg \
LCD/lvgl/lvgl-v8.3/src/extra/libs/freetype \
LCD/lvgl/lvgl-v8.3/src/extra/libs/fsdrv \
LCD/lvgl/lvgl-v8.3/src/extra/libs/gif \
LCD/lvgl/lvgl-v8.3/src/extra/libs/png \
LCD/lvgl/lvgl-v8.3/src/extra/libs/qrcode \
LCD/lvgl/lvgl-v8.3/src/extra/libs/rlottie \
LCD/lvgl/lvgl-v8.3/src/extra/libs/sjpg \
LCD/lvgl/lvgl-v8.3/src/extra \
LCD/lvgl/lvgl-v8.3/src/extra/others/fragment \
LCD/lvgl/lvgl-v8.3/src/extra/others/gridnav \
LCD/lvgl/lvgl-v8.3/src/extra/others/ime \
LCD/lvgl/lvgl-v8.3/src/extra/others/imgfont \
LCD/lvgl/lvgl-v8.3/src/extra/others/monkey \
LCD/lvgl/lvgl-v8.3/src/extra/others/msg \
LCD/lvgl/lvgl-v8.3/src/extra/others/snapshot \
LCD/lvgl/lvgl-v8.3/src/extra/themes/basic \
LCD/lvgl/lvgl-v8.3/src/extra/themes/default \
LCD/lvgl/lvgl-v8.3/src/extra/themes/mono \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/animimg \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/calendar \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/chart \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/colorwheel \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/imgbtn \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/keyboard \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/led \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/list \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/menu \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/meter \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/msgbox \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/span \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/spinbox \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/spinner \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/tabview \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/tileview \
LCD/lvgl/lvgl-v8.3/src/extra/widgets/win \
LCD/lvgl/lvgl-v8.3/src/font \
LCD/lvgl/lvgl-v8.3/src/hal \
LCD/lvgl/lvgl-v8.3/src/misc \
LCD/lvgl/lvgl-v8.3/src/widgets \
LCD/lvgl/lvgl-v8.3/tests/makefile \
LCD/lvgl/lvgl-v8.3/tests/src \
LCD/lvgl/lvgl-v8.3/tests/src/test_cases \
LCD/lvgl/lvgl-v8.3/tests/src/test_fonts \
LCD/lvgl/lvgl-v8.3/tests/unity \
Motor_Control \
UltraSonic_Sensors \

